### ISSUE TITLE
Version with EBB 36 CAN V1.1 Holder

### ISSUE THREAD

**Issue by pforrmi** [elcrni/Voron-Mods#5]
Hi,

first thanks very much for this amazing design! I really like it.
I'm using the Stealtburner with the BIGTREETECH EBB 36 CAN V1.1. Is it possible you can adjust it to mount it at the toolhead?

Bests
Michael

**Comment by ReXT3D** [comment]
FWIW, I am targeting the same tool head configuration using Stealthburner, Orbiter 2 & EBB36 (or alternatively EBB42).  I have defined what I believe is a reasonably optimal design configuration, but it would require shifting the complete Orbiter 2 assembly up by about 6 mm in order to clear interference highlighted below:

![Orbiter 2 0 CW2 Mount REV2v41 EBB36](https://user-images.githubusercontent.com/77699888/198840953-a522627e-790d-4161-a2c4-8ecd02f23fe6.png)

From design requirements perspective, I prefer to retain the chain and I feel very strongly that active cooling is required for the stepper motor and for the EBB36 in order to improve long term reliability in a heated chamber.  The above sample layout moves the chain end point by the length of two links and includes a location for 3010 cooling fan.

EDIT: Naturally the EBB could also be installed in an orthogonal orientation by mounting to a dedicated bracket instead of the motor standoffs.  This could allow installation without relocating the Orbiter upwards.

**Comment by ReXT3D** [comment]
Just had another look.  Placing the EBB36 orthogonally would indeed work much better and it appears to need only reasonably small changes to your original design:

1. Revised **Chain Anchor** for new chain end location and to support one of the two EBB36 mounting points
2. Revised **Rear Body Orbiter 2** to support the second EBB36 mounting point with minimal fan flow obstruction
3. Revised **Cable Cover for PCB** to support installation of 3010 fan

![Orbiter 2 0 CW2 Mount REV2v41 EBB36 Orthogonal](https://user-images.githubusercontent.com/77699888/198841994-a5494e9a-ada4-4d6b-90bf-1751adbcd63a.png)

Unfortunately I am still in the process of building my 2.4 and it would be a while before I can have a go at making these changes.

**Comment by ReXT3D** [comment]
Another feasibility concept with EBB42.  It is awfully tight in there, and overall the "stealth" surface geometry makes it a bit challenging to work with TBH...

![image](https://user-images.githubusercontent.com/77699888/200122361-25dcbf53-9a57-46f7-9b07-263710a5a0d0.png)

**Comment by pforrmi** [comment]
I really like your designs! Thanks for sharing.

I'm using the EBB36 for now without a cable chain. Also thinking that a fan is not necessary for cooling cause I printed some hours with enclosed 2.4 and no bad things happened with inside temperature at about 50 degrees.

Do you uploaded your designs yet?

**Comment by ReXT3D** [comment]
> Do you uploaded your designs yet?

Thank you for your comments.  Note that this is only a proof of concept & fitment check and not a design.  I just played with F360 using author's supplied model to identify potential installation concepts that would meet my requirements.

> Also thinking that a fan is not necessary for cooling cause I printed some hours with enclosed 2.4 and no bad things happened with inside temperature at about 50 degrees.

As I mentioned before, I feel very strongly about the need for forced cooling of the stepper and the toolboard.  Orbiter 2 stepper runs very hot even on my unenclosed CR-10S Pro in a cool basement.  Having the stepper additionally enclosed with plastic brackets & covers and in a heated chamber will bring its temperature very close to ABS deflection temperature and likely above ABS+ glass transition.  In addition, a lot of the stepper heat is also transmitted into the Bondtech gears, which is not ideal for the filament.  Finally, electronics failure rate (unreliability) increases exponentially with operating temperature and therefore you always want to keep the electronics as far away from their design limits as possible.  And I doubt that BTT (or Mellow for that matter) have done any thorough thermal derating analysis of their boards...

**Comment by mstawick** [comment]
FYI, on the orbiter project page (https://orbiterprojects.com/orbiter-v2-0/), you can expand the firmware section, and there's the interesting part under `3.7 Motor current vs extruder performance and temperature`. I've run some tests with NTC glued to the orbiter motor, and the provided numbers seem to be accurate (not that I would assume them not to be, but better test and be safe than sorry...).

This means that in an enclosure, it's either active cooling, reduced current, or melted Stealthburner ;)

(though I'll probably experiment with a blower fan, as opposed to an axial one)

**Comment by ReXT3D** [comment]
Thanks for the empirical data.  I have not measured the stepper temperatures on my installation, but having interacted with Robert I also have no doubts that his data is as accurate and unbiased as he is able to collect.

I have been using reduced run current of 0.65 since I do not need the full performance capability of Orbiter 2.  Even at this setting the stepper runs subjectively quite hot and after longer prints the Bondtech gears are also hot to touch.

FWIW I feel that axial fan is quite adequate in this application because the flow path can be designed with minimal restrictions and very high delta-P capability of a radial fan is not necessary.  But of course if you already have one on hand it's a different story.

**Comment by elcrni** [comment]
Thank you for your efforts and an interesting solution. 
I am now working on adding the CAN board. Your solution for the fan and the cable cover looks nice, but are you cooling the motor or the board with that variant? 
Perhaps you could share your files, cable cover that is.
many thanks

> Just had another look. Placing the EBB36 orthogonally would indeed work much better and it appears to need only reasonably small changes to your original design:
> 
> 1. Revised **Chain Anchor** for new chain end location and to support one of the two EBB36 mounting points
> 2. Revised **Rear Body Orbiter 2** to support the second EBB36 mounting point with minimal fan flow obstruction
> 3. Revised **Cable Cover for PCB** to support installation of 3010 fan
> 
> ![Orbiter 2 0 CW2 Mount REV2v41 EBB36 Orthogonal](https://user-images.githubusercontent.com/77699888/198841994-a5494e9a-ada4-4d6b-90bf-1751adbcd63a.png)
> 
> Unfortunately I am still in the process of building my 2.4 and it would be a while before I can have a go at making these changes.

**Comment by ReXT3D** [comment]
> Your solution for the fan and the cable cover looks nice, but are you cooling the motor or the board with that variant?
> Perhaps you could share your files, cable cover that is.
> many thanks

Hello, I am glad to see that you are able to work on the CAN board implementation.  As I noted earlier to **pforrmi** this was really just a form & fit proof of concept rather than a design.  I was trying to figure out what placement would be feasible and if things could fit...

With respect to the fan, it can be placed to cool both, the stepper body and the back side of the EBB board (correctly installed TMC drivers dissipate the heat through the back side into the PCB).  In my attempt to place the fan with minimal changes to the cover, I picked this potential position:

![Orbiter 2 0 CW2 Mount REV2v41 v5](https://user-images.githubusercontent.com/77699888/201987489-6bdd73a1-f64e-4963-9ded-0e803de21478.png)

But if one were to make larger scope changes to the cover, the fan could be moved another 1-2 mm towards the back of the printer to increase the EBB back-side cooling.

**Comment by ReXT3D** [comment]
I am attaching the cover concept STEP file in case you find it useful for positioning the fan.  It also includes a 3010 fan model that I put together a while ago from bits and pieces I found online.  As I said before, this is just a concept and the cover needs detailed design work to allow fan attachment, etc.

[Fan Cover Concept.zip](https://github.com/elcrni/Voron-Mods/files/10043202/Fan.Cover.Concept.zip)

**Comment by pireybr** [comment]
> I am attaching the cover concept STEP file in case you find it useful for positioning the fan. It also includes a 3010 fan model that I put together a while ago from bits and pieces I found online. As I said before, this is just a concept and the cover needs detailed design work to allow fan attachment, etc.
> 
> [Fan Cover Concept.zip](https://github.com/elcrni/Voron-Mods/files/10043202/Fan.Cover.Concept.zip)

Please release a final version of it :)

**Comment by MLeal91** [comment]
@elcrni @ReXT3D waiting for this too, orbiter is awsome and with canbus is the best but at momment dont have any mount to can with orbiter. will wait for this

**Comment by elcrni** [comment]
Hi all, 

1st revision of the EBB36 CAN mount is available for testing now. Keep in mind, there is no cable chain mount, only the PG7/Umbilical mount, for now.

Files are here:
https://layerguru.com/wp-content/uploads/2022/12/EBB36_SB_Orbiter_R1.zip

I would appreciate the feedback. Many thanks.

![image](https://user-images.githubusercontent.com/74976689/209835355-df5fdef8-4f5f-419a-91a1-1db5e53e74ac.png)
![image](https://user-images.githubusercontent.com/74976689/209835438-dc2861b0-d6bb-4568-bdc2-a62ea93d5cfb.png)

**Comment by MLeal91** [comment]
> Hi all,
> 
> 1st revision of the EBB36 CAN mount is available for testing now. Keep in mind, there is no cable chain mount, only the PG7/Umbilical mount, for now.
> 
> Files are here: https://layerguru.com/wp-content/uploads/2022/12/EBB36_SB_Orbiter_R1.zip
> 
> I would appreciate the feedback. Many thanks.
> 
> ![image](https://user-images.githubusercontent.com/74976689/209835355-df5fdef8-4f5f-419a-91a1-1db5e53e74ac.png) ![image](https://user-images.githubusercontent.com/74976689/209835438-dc2861b0-d6bb-4568-bdc2-a62ea93d5cfb.png)

it is something now :) simple design and functional .... you will work on solution to use chain?

**Comment by elcrni** [comment]
> it is something now :) simple design and functional .... you will work on solution to use chain?

Yes, cable chain version will follow.

**Comment by elcrni** [comment]
Cable chain mount ready for testing. Please note: 1 or 2 chain links will have to be removed as the chain needs to be a bit shorter.

Files are here, properly oriented, just import and print
https://layerguru.com/wp-content/uploads/2022/12/EBB36_cable_chain_mount.zip

![image](https://user-images.githubusercontent.com/74976689/209954427-388469c5-b983-48e5-bd7b-a88b9e7564aa.png)
![image](https://user-images.githubusercontent.com/74976689/209954446-e26bfc1d-25ab-4172-9cdc-0050947133fe.png)
![image](https://user-images.githubusercontent.com/74976689/209954570-f5a23b29-aa31-4ada-97e8-965bb9b98d05.png)

**Comment by MLeal91** [comment]
just wait for usb cable to connect this :)
Cable Cover for PCB 3010 fan is for future idea? i like idea of cooling stepper motor and can

**Comment by ndng28** [comment]
Hey thanks for working on this. Some feeedback...the CANbus mount oscillates during input-shaper tests and I am getting some wild data. I think it needs a third stand-off screw or something to provide additional rigidity. Also the CANBus needs to be mounted perpendicular to the axis.

https://github.com/KayosMaker/CANboard_Mounts

**Comment by elcrni** [comment]
> Hey thanks for working on this. Some feeedback...the CANbus mount oscillates during input-shaper tests and I am getting some wild data. I think it needs a third stand-off screw or something to provide additional rigidity. Also the CANBus needs to be mounted perpendicular to the axis.
> 
> https://github.com/KayosMaker/CANboard_Mounts

Yes, i am aware of the ADXL issue as the board is rotated 90 degrees but that's pretty much the only way to mount it. The reason you are getting wild IS data is the rotation of the board and not the mount itself. Perhaps you could use separate ADXL.
